/**
 * @type {import('lodash').merge}
 */
 const _merge = require('lodash.merge');


 import { fluidExtractor, fluidCorePlugins, defaultThemeScreensInRems, defaultThemeFontSizeInRems } from 'https://esm.sh/fluid-tailwind?bundle-deps&external=fs';
 import flowtitude from 'https://esm.sh/flowtitude@0.0.2';
 
 /**
  * The Tailwind CSS configuration required by the SIUL plugin.
  *
  * @type {import('tailwindcss').Config} 
  */
 let siul = {};
 
 /* The autogenerated Tailwind CSS configuration from the Wizard goes below. */
 
 //-@-wizard
 
 /* Your custom Tailwind CSS configuration goes below. */
 
 function cssVars({ addUtilities, theme }) {
   function extractVars(obj, group = '', prefix) {
     return Object.keys(obj).reduce((vars, key) => {
       const value = obj[key];
       key = key.replaceAll('.', '_').replaceAll('/', '__');
 
       const cssVariable = key === "DEFAULT" ? `--ft-${prefix}${group}` : `--ft-${prefix}${group}-${key}`;
 
       const newVars =
         typeof value === 'string'
           ? { [cssVariable]: value }
           : extractVars(value, `-${key}`, prefix);
 
       return { ...vars, ...newVars };
     }, {});
   }
   addUtilities({
       ':root': {
         ...extractVars(theme('colors'), '', 'color'),
         ...extractVars(theme('screens'), '', 'screen'),
         ...extractVars(theme('fontSize'), '', 'text'),
         ...extractVars(theme('fontWeight'), '', 'font'),
         ...extractVars(theme('lineHeight'), '', 'leading'),
         ...extractVars(theme('letterSpacing'), '', 'traking'),
         ...extractVars(theme('borderWidth'), '', 'border'),
         ...extractVars(theme('borderRadius'), '', 'rounded'),
         ...extractVars(theme('width'), '', 'space'),
         ...extractVars(theme('minWidth'), '', 'min-space'),
         ...extractVars(theme('maxWidth'), '', 'max-space'),
         ...extractVars(theme('zIndex'), '', 'z'),
         ...extractVars(theme('opacity'), '', 'opacity'),
       }
     });
 }
 
 /**
  * @type {import('tailwindcss').Config} 
  */
 let presetConfig = {
     darkMode: 'class',
     content: {
         files: [],
         extract: fluidExtractor()
     },
     theme: {
         fontSize: defaultThemeFontSizeInRems,
         screens: defaultThemeScreensInRems,
 
         nightwind: {
             transitionDuration: "500ms", // default '300ms'
             colorScale: {
                 50: 950,
                 100: 900,
                 200: 800,
                 300: 700,
                 400: 600,
                 500: 500,
                 600: 400,
                 700: 300,
                 800: 200,
                 900: 100,
                 950: 50,
             },
         },
 
         extend: {
             fontFamily: {				
                 'body': ['var(--ft-font-body)'],
                 'display': ['var(--ft-font-display)'],
             },
         },
     },
     plugins: [
         cssVars,
         fluidCorePlugins,
         flowtitude,
         require("@tailwindcss/container-queries"),
         require("nightwind"),
     ],
 };
 
 /* That's all, stop editing! Happy building. */
 
 _merge(siul, presetConfig);
 